title: "Perceval Beja-Battais"
description: "PhD Student – Machine Learning & Optimization"
theme: jekyll-theme-cayman

# URL de ton site (GitHub va la générer automatiquement)
baseurl: "" 
url: "https://pbb.github.io/mon-site"  

# Infos auteur (facultatif mais utile pour référencement)
author:
  name: "Perceval Beja-Battais"
  email: "perceval.beja-battais@ens-paris-saclay.fr"
  linkedin: "https://www.linkedin.com/in/perceval-beja-battais-b043331b9/"

# Options de Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation (si tu veux un menu automatique)
nav:
  - title: "Accueil"
    url: "/"
  - title: "Projets"
    url: "/projets"
  - title: "Contact"
    url: "/contact"
